FROM golang:1.24.3

WORKDIR /app

# Copy faucet project
COPY faucet /app/faucet
WORKDIR /app/faucet

# Download dependencies and build
RUN go mod download
RUN go build -o faucet

# Create database directory
RUN mkdir -p /root/.faucet

# Make sure the binary is executable
RUN chmod +x faucet

# The container will be run interactively
# To use: docker run -it --rm faucet /bin/bash
# Then you can run ./faucet with your desired parameters 