services:
    bitcoin:
        build:
            context: .
            dockerfile: Dockerfile.bitcoin
        ports:
            - "18332:18332"
        volumes:
            - bitcoin-data:/root/.bitcoin
        networks:
            - testnet-network

    watcher:
        build:
            context: .
            dockerfile: Dockerfile.watcher
        depends_on:
            - bitcoin
        environment:
            - RPC_URL=http://bitcoin:18332
            - RPC_USER=user
            - RPC_PASS=pass
        volumes:
            - faucet-data:/root/.faucet
        networks:
            - testnet-network

    faucet:
        build:
            context: .
            dockerfile: Dockerfile.faucet
        depends_on:
            - bitcoin
        environment:
            - RPC_URL=http://bitcoin:18332
            - RPC_USER=user
            - RPC_PASS=pass
        volumes:
            - faucet-data:/root/.faucet
        networks:
            - testnet-network
        stdin_open: true # equivalent to docker run -i
        tty: true # equivalent to docker run -t
        command: /bin/bash

volumes:
    bitcoin-data:
    faucet-data:

networks:
    testnet-network:
        driver: bridge
